### ISSUE TITLE
Choosing option.sass:false still outputs scss files

### ISSUE THREAD

**Issue by ssylvia** [jubalm/grunt-fontello#9] opened 2014-04-04 19:01 UTC

**Comment by ericcornelissen** [comment] 2017-09-02 13:47
I'm unable to reproduce this issue and I think it comes from the fact that the option is not called `sass` but `scss`, see [the README](https://github.com/jubalm/grunt-fontello#optionsscss).

Closing this issue for now, if the problem still exist feel free to reopen 🙂

**Closed by ericcornelissen** 2017-09-02 13:47 UTC
